Fix ensure_packages error
The ceilometer::collector class calls ensure_packages()
on a single package name, but the package name is provided
as a string rather than a one-element array.  This causes an
error of the form:

Error: ensure_packages(): Requires array given (String) at
/usr/share/puppet/modules/ceilometer/manifests/collector.pp:16

This patch corrects the error by passing an array instead
of a string.

Change-Id: I96cedf7561af29d92924746881c52bdd1502365f
Closes-Bug: #1292775