puppet4: fix ordering for compute agent
When managing the POSIX user for Ceilometer, we need to make sure
ceilometer-common and libvirt are installed before, otherwise catalog
will fail on Puppet4 with:

Error: Could not set groups on user[ceilometer]: Execution of
'/usr/sbin/usermod -G libvirtd,nova ceilometer' returned 6: usermod:
group 'libvirtd' does not exist

It's an orchestration issue, fixed by this patch.

Change-Id: I31daa60fa110bed68a30e576500f82ed69d30904